name: Lint Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-code-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_LINTER: false  # Disable linting
          RUN_FORMATTER: true # Enable formatting
          FIX_CLANG_FORMAT: true
          FILTER_REGEX_INCLUDE: '.*/(include|src|doc)/.*'
          FILTER_REGEX_EXCLUDE: '^(third_party|assets)/.*' # Exclude these directories
          VALIDATE_CPLUSPLUS: true
          CLANG_FORMAT_EXTENSIONS: 'cpp,h,hpp'  # List of extensions to be formatted
          ACTIONS_RUNNER_DEBUG: true
