name: Lint Code Base

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-code-base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_LINTER: false  # Disable linting
          RUN_FORMATTER: true # Enable formatting
          FORMAT_ONLY: true
          FILTER_DIRS: 'include/,src/,doc/' # Only format these dirs
          SKIP_DIRS: 'third_party/,assets/' # Skip these dirs
